#include "unity.h"
#include "led.h"
#include "Mockgpio.h"  // <- This will be generated by CMock

void setUp(void) {
    // Called before each test
}

void tearDown(void) {
    // Called after each test
}

void test_led_on_should_turn_gpio_high(void) {
    gpio_set_high_Expect(13);
    led_on();
}

void test_led_off_should_turn_gpio_low(void) {
    gpio_set_low_Expect(13);
    led_off();
}

int main(void) {
    UNITY_BEGIN();

    RUN_TEST(test_led_on_should_turn_gpio_high);
    RUN_TEST(test_led_off_should_turn_gpio_low);

    return UNITY_END();
}
