#include "unity.h"
#include "led.h"       // <- code under test
#include "Mockgpio.h"  // <- This will be generated by CMock

// SPI Test
#include "spi.h"
#include "Mockspi.h"  // This is generated by CMock

// Adder Test
#include "adder.h"

void setUp(void) {
    // Called before each test
}

void tearDown(void) {
    // Called after each test
}

void test_add_two_positive_numbers(void) {
    TEST_ASSERT_EQUAL(5, add(2, 3));
}

void test_add_negative_numbers(void) {
    TEST_ASSERT_EQUAL(-5, add(-2, -3));
}

void test_send_message_to_device_should_call_spi_send_data_for_each_char(void) {
    const char *message = "Hello";
    int device_id = 1;

    // Set the expectations
    spi_send_data_Expect(device_id, "H");
    spi_send_data_Expect(device_id, "e");
    spi_send_data_Expect(device_id, "l");
    spi_send_data_Expect(device_id, "l");
    spi_send_data_Expect(device_id, "o");

    // Call the function under test
    // send_message_to_device(device_id, message);
}

void test_led_on_should_turn_gpio_high(void) {
    gpio_set_high_Expect(13);
    led_on();
}

void test_led_off_should_turn_gpio_low(void) {
    gpio_set_low_Expect(13);
    led_off();
}

int main(void) {
    UNITY_BEGIN();
    
    RUN_TEST(test_add_two_positive_numbers);
    RUN_TEST(test_add_negative_numbers);

    RUN_TEST(test_led_on_should_turn_gpio_high);
    RUN_TEST(test_led_off_should_turn_gpio_low);

    // SPI Tests
    RUN_TEST(test_send_message_to_device_should_call_spi_send_data_for_each_char);

    return UNITY_END();
}
